name: Check Docs

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  CARGO_TERM_COLOR: always

jobs:
  rustdoc:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - uses: actions-rs/toolchain@v1
        name: Install rust toolchain
        with:
          toolchain: stable
          override: true

      - uses: Swatinem/rust-cache@v2
        name: Add caching

      - uses: actions-rs/cargo@v1
        name: Check Documentation with Rustdoc
        with:
          command: doc
          args: --verbose --no-deps
